name: zcli-bulk-action
description: Github Action to deploy Zendesk Apps using ZCLI to multiple instances.
inputs:
  PATH:
    description: Path to the app dist directory.
    required: true
    default: "dist"
  ENVIRONMENT:
    description: "Environment"
    default: ${{github.ref_name == 'main' && 'production' || 'staging'}}
runs:
  using: "node16"
  main: "dist/index.js"
